### ISSUE TITLE
FEATURE: Public Key Pinning (HPKP)

### ISSUE THREAD

**Issue by lewisgoddard** [eustasy/bubbly#8]
### Roadmap
- [ ] Generate hashes when the keys are updated.
- [ ] Replace hashes for automatic HPKP configuration in `nginx-config/directive/bubbly_hpkp.conf`
- [ ] Default to report only for safety, with documented options and warnings in-configuration.
- [ ] Secondary option with short life, due to short certificate life.
- [ ] Add documentation to `README.md`
### References
- https://developer.mozilla.org/en/docs/Web/Security/Public_Key_Pinning
- https://wiki.mozilla.org/SecurityEngineering/Public_Key_Pinning
- https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning
- https://tools.ietf.org/html/rfc7469

**Comment by lewisgoddard** [comment]
Google is abandoning HPKP in favour of the Expect-CT header.
- https://www.theregister.co.uk/2017/10/30/google_hpkp/

**Comment by lewisgoddard** [comment]
See #16 for Expect-CT support.
